graph TD;

JavaScript 

JavaScript --> browser
browser --> IE
browser --> firefox
browser --> chrome

JavaScript --> NodeJS

JavaScript --> ES5
JavaScript --> ES6 

NodeJS --> TypeScript
NodeJS --> Flow 
NodeJS --> JSX
